[app]
primary_region = "gig"

[build]

[env]
PYTHONPATH = "/app"
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
interval = "15s"
timeout = "2s"
grace_period = "5s"
method = "GET"
path = "/api/health"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256